### ISSUE TITLE
Laravel 7 Support

### ISSUE THREAD

**Issue by litan1106** [Hunternnm/laravel-roadrunner#5]
Problem 1
    - Conclusion: don't install hunternnm/laravel-roadrunner v2.0.3
    - Conclusion: don't install hunternnm/laravel-roadrunner v2.0.2
    - Conclusion: don't install hunternnm/laravel-roadrunner v2.0.1
    - Conclusion: remove laravel/framework v7.1.0
    - Installation request for hunternnm/laravel-roadrunner ^2.0 -> satisfiable by hunternnm/laravel-roadrunner[2.0, v2.0.1, v2.0.2, v2.0.3].
    - Conclusion: don't install laravel/framework v7.1.0

**Comment by porozhnyy** [comment]
Added support for Laravel in release 2.0.4

**Comment by litan1106** [comment]
thanks
